FROM python:3.11-alpine

WORKDIR /src

RUN apk update && \
    apk add --no-cache gcc musl-dev libffi-dev



RUN pip install fastapi[standard]
RUN pip install uvicorn[standard]
RUN pip install yfinance==0.2.43

COPY /src /src/

CMD ["fastapi", "run", "main.py", "--port", "80"]